### PR TITLE
Tighten up some pixels

### PR DESCRIPTION
**Pull request by sartak**
Reduces the vertical space for the view command.

Before:

```
Colemak (KLCord) (5 likes)
  q w f p g  j l u y ;  
  a r s t d  h n e i o '
  z x c v b  k m , . /  

MONKEYRACER:
  Alt: 21.46%
  Rol: 43.82%   (In/Out: 22.91% | 20.91%)
  One:  2.54%   (In/Out:  1.47% |  1.07%)
  Red:  6.85%   (Bad:     1.79%)

  SFB: 1.40%
  SFS: 8.38%

  LH/RH: 44.12% | 55.88%
```

After:

```
Colemak (KLCord) (5 likes)
  q w f p g  j l u y ;  
  a r s t d  h n e i o '
  z x c v b  k m , . /  

MONKEYRACER:
  Alt: 21.46%
  Rol: 43.82%   (In/Out: 22.91% | 20.91%)
  One:  2.54%   (In/Out:  1.47% |  1.07%)
  Red:  6.85%   (Bad:     1.79%)
  SFB/SFS: 1.40% | 8.38%
  LH/RH: 44.12% | 55.88%
```

### CODE REVIEW

**Review by Dainternetdude — CHANGES_REQUESTED** [review]
please change "sfb/dfb" to "sfb/sfs"

**Comment by sartak** [comment]
> please change "sfb/dfb" to "sfb/sfs"

That's a reasonable suggestion but out of scope for this PR!

**Review by Dainternetdude — APPROVED** [review]

**Comment by Dainternetdude** [comment]
LGTM! 👍

**Comment by sartak** [comment]
I ended up changing to SFS to resolve the merge conflict, since this PR has been sitting in limbo for so long

**Comment by Dainternetdude** [comment]
sure sure

**Pull request merged**
